"""test9

Revision ID: 3335417036cb
Revises: 0c0dfd9f42d0
Create Date: 2022-07-23 17:02:11.496592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3335417036cb'
down_revision = '0c0dfd9f42d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
