"""test7

Revision ID: 34409d9ce0c8
Revises: e9ef95d9a226
Create Date: 2022-07-18 20:58:37.116580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34409d9ce0c8'
down_revision = 'e9ef95d9a226'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'book_id')
    op.drop_column('users', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
