"""test5

Revision ID: 7b5d63927046
Revises: e64a6bf132d4
Create Date: 2022-07-18 13:12:12.947197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b5d63927046'
down_revision = 'e64a6bf132d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Books', sa.Column('book_id', sa.Integer(), nullable=True))
    op.add_column('Users', sa.Column('user_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'user_id')
    op.drop_column('Books', 'book_id')
    # ### end Alembic commands ###
