"""test3

Revision ID: d0924b1a0fd8
Revises: c4d026292bda
Create Date: 2022-07-18 12:55:46.623764

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd0924b1a0fd8'
down_revision = 'c4d026292bda'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Books', 'book_id')
    op.drop_column('Users', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.add_column('Books', sa.Column('book_id', postgresql.UUID(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
