"""test4

Revision ID: e64a6bf132d4
Revises: d0924b1a0fd8
Create Date: 2022-07-18 12:58:09.340658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e64a6bf132d4'
down_revision = 'd0924b1a0fd8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Books', 'is_sale')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Books', sa.Column('is_sale', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
